version: '3'
services:
  web:
    image: hitalos/laravel:latest
    ports:
      - 82:80
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: dbname
      DB_USERNAME: fran
      DB_PASSWORD: fran
      DB_CONNECTION: mysql
  db:
    image: mysql:5.7
    volumes:
      - ~/.laradock/data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      # with mysql
      MYSQL_DATABASE: dbname
      MYSQL_USER: fran
      MYSQL_PASSWORD: fran
      MYSQL_ROOT_PASSWORD: fran
  phpmyadmin:
    #build: ./phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - /sessions
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=paroot
      - MYSQL_PASSWORD=paroot
      - MYSQL_ROOT_PASSWORD=paroot
    ports:
      - "8080:80"
    depends_on:
      - db


